//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class classify
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string LongName { get; set; }
        public string Type { get; set; }
        public string ImgUrl { get; set; }
        public string Describe { get; set; }
        public Nullable<int> IsDel { get; set; }
        public Nullable<int> InsertUser { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string ImgUrl2 { get; set; }
    }
}
