//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeForce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class download
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string Describe { get; set; }
        public string Type { get; set; }
        public string Lang { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
