//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeForce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Classify { get; set; }
        public string ImgUrl { get; set; }
        public string Features { get; set; }
        public Nullable<int> InsertUser { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<int> IsDel { get; set; }
        public string PDFSoureName { get; set; }
        public string Lang { get; set; }
        public string PDF { get; set; }
        public string Quality { get; set; }
        public string Describe { get; set; }
        public string ProductID { get; set; }
        public string ProductCode { get; set; }
        public Nullable<int> Index { get; set; }
    }
}
